### ISSUE TITLE
Find the proper place for custom web-endpoint integration hook in the android stack and build the ROM

### ISSUE THREAD

**Issue by dchristiansen** [ksefcovic/CYBR4580#3]
This should be the driver that is used before the NIC is identified and the correct driver is installed. Need to make a fork of this repo.

**Comment by aaronwurtele** [comment]
It doesn't appear that manufacturers use a general purpose NIC driver, but instead create their own kernels for each phone with the necessary drivers. Instead we will move to connect to the server when the Android device connects to a network -- the connection back to our server will take place after the device is given an IP by the DHCP server.

**Comment by dchristiansen** [comment]
@aaronwurtele are we still flashing a custom ROM to the device? If so I think we still need to find the ROM for the specific chipset on the phone.

**Comment by aaronwurtele** [comment]
@dchristiansen Yes we are still doing to be flashing a custom ROM to the device. We should grab the Android 10 ROM for the Original Pixel XL that you have

**Comment by aaronwurtele** [comment]
https://source.android.com/setup/build

**Comment by aaronwurtele** [comment]
I created documentation on how to download the AOSP source tree and open it in android studio in commit 8a98f63. The file "WifiManager.java" is located in "./frameworks/base/wifi/java/android/net/wifi/WifiManager.java".

**Comment by aaronwurtele** [comment]
https://developer.android.com/reference/android/net/wifi/package-summary

This might be helpful in determining what each of the files listed at https://community.nxp.com/docs/DOC-93603 do.

**Comment by aaronwurtele** [comment]
I changed the documentation for how to get up and running in ae64eb8 based off of information from https://www.protechtraining.com/blog/post/aosp-sources-in-the-ide-860#targetText=IntelliJ%20%2B%20Android%20Studio&targetText=Choose%20to%20open%20an%20existing,fully%20index%20the%20source%20files.

**Comment by aaronwurtele** [comment]
Update: I couldn't get the build to work on Windows Subsystem for Linux, so I have to do the whole thing again in my Ubuntu VM.

**Comment by MLHale** [comment]
Is this still an issue - given that you were looking further up in the android stack to add your code?

**Comment by aaronwurtele** [comment]
We have repurposed this issue for finding the correct spot to put the code

**Comment by MLHale** [comment]
ok, that makes sense. I changed the title.

**Comment by dchristiansen** [comment]
There is a function to get the MAC address in the android.net.wifi WifiInfo class.  (https://developer.android.com/reference/android/net/wifi/WifiInfo.html#getMacAddress())

**Comment by aaronwurtele** [comment]
https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback.html#onAvailable(android.net.Network)

It looks like we are probably going to use the onAvailable() function from the ConnectivityManager.NetworkCallback class -- "Called when the framework connects and has declared a new network ready for use."

The function gets passed a network object which is described: "Identifies a Network. This is supplied to applications via ConnectivityManager.NetworkCallback in response to the active ConnectivityManager#requestNetwork or passive ConnectivityManager#registerNetworkCallback calls. It is used to direct traffic to the given Network, either on a Socket basis through a targeted SocketFactory or process-wide via ConnectivityManager#bindProcessToNetwork."

**Comment by aaronwurtele** [comment]
The NetworkCallback class is located on line 3,221 in the ConnectivityManager class and the onAvailable function is overloaded, and they are on lines 3,250 and 3,276.

**Comment by aaronwurtele** [comment]
I've spent the last couple of days trying to get it to work. It turns out you need to a normal "make". That process took just over 4 hours. 

However, you can't run the emulator in a VM. 

I just found out that you can make a folder in Windows 10 case-sensitive. This should allow us to use the Windows Subsystem for Linux and the android emulator.

**Comment by aaronwurtele** [comment]
nsjail errors out during the architecture configuration, which prevents the build from completing... I'll be installing Linux on a secondary laptop and trying to complete this on that.

**Comment by aaronwurtele** [comment]
Installed it on a secondary laptop, pulled the code (since attempting to copy the tree produces errors), and tried to compile it. The laptop continually crashed because it only had 8gb of RAM.

I found an extra SSD around my house and installed Ubuntu on my desktop. Currently pulling the source tree. There shouldn't be any problems with this one, as it has 8 threads and 16gb of RAM. I didn't try this earlier, as it's a significant inconvenience to me.

**Comment by aaronwurtele** [comment]
I was able to get the source to fully compile and the emulator running.

**Comment by aaronwurtele** [comment]
I ran the custom ROM in the emulator and outputted logcat to a file. I turned both the cellular and wifi networks off, disconnected from the network, reconnnected to it, forgot the network, reconnected to it, and put the phone in and out of airplane mode. The logcat output did not include the string that we have Log.i outputting, meaning that onAvailable() was not called, and there were no mentions of ConnectivityMonitor or NetworkCallback. I did however notice that ConnectivityService had an output whenever a network status changed -- this includes when the network being used was changed and when networks were connected/disconnected, so this might be the next class to take a look at.

**Comment by aaronwurtele** [comment]
I found a new spot to put it based off of the logcat output. In ConnectivityService.java, there is a function called updateNetworkInfo() that gets called whenever there is a change in network connectivity (like null to connecting, connecting to connected, connected to null -- this is for both cellular and wifi). I am adding a conditional statement that will add to the logcat output if the network goes from connecting to connected. I still have to compile the ROM and test, but I think that this will almost certainly be a better place to put the code. Anytime there was a change in the network connectivity of the emulated system, this function was the first to report the connectivity change in logcat.

**Comment by aaronwurtele** [comment]
[LOGCAT.txt](https://github.com/ksefcovic/CYBR4580/files/3764905/LOGCAT.txt)

By the way, this is the logcat output

**Comment by MLHale** [comment]
nice find!

**Comment by aaronwurtele** [comment]
After much trial-and-error, I found that the emulator was not running the custom ROM (system image) but instead the default image for the Pixel XL API 29 device. I started running ours using a different flag and updated the emulator documentation in ed6198a. The problem now is that there is now logcat output. I am currently troubleshooting this problem.

**Comment by aaronwurtele** [comment]
After more troubleshooting, I found an updated note that the android-10.0.0_r3 branch is not supported for Pixel XL, I will try  android-10.0.0_r2. Additonally, I have made some progress on the android emulator issue and updated documentation in 8fd7057.

**Comment by aaronwurtele** [comment]
I'll leave this issue open, until we can verify which of the fuctions (onAvailable(), updateNetworkInfo(), or makeDefault()) is the correct one to hijack. Issue #17 is where I will place the rest of the android emulator discussion

**Comment by aaronwurtele** [comment]
I was able to get the emulator running and I can see all of the changes I made to the log outputs. I will upload the log and decide which of the placements is best.

**Comment by aaronwurtele** [comment]
Here is the new logfile -- it appears that the bottom of makeDefault is the best place to put our endpoint code, since it makes all of the calls to set up the network connection. 
[emulator.log](https://github.com/ksefcovic/CYBR4580/files/3802738/emulator.log)

**Comment by aaronwurtele** [comment]
In class I added some code to make a connection to http://android.com at the bottom of makeDefault, as a means of testing the location. It was successful and produced:
`11-05 21:17:01.989  1759  2349 D ConnectivityService - AW: <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8"><TITLE>302 Moved</TITLE></HEAD><BODY><H1>302 Moved</H1>The document has moved<A HREF="https://www.android.com/">here</A>.</BODY></HTML>`

**Comment by aaronwurtele** [comment]
After testing last week, this has been confirmed to be the best place.
