### ISSUE TITLE
Determine how to flash a modified driver to android device

### ISSUE THREAD

**Issue by dchristiansen** [ksefcovic/CYBR4580#4]
Once we find an AOSP NIC driver we need to figure out how to flash the updated driver to the android device (either emulated or other devices)

**Comment by dchristiansen** [comment]
Once we create a compiled ROM is should be pretty simple to flash a ROM using ADB unlock the bootloader, install a custom recovery environment like TWRP. Move the ROM files onto the phone boot into TWRP recovery. Wipe the phone, then install the ROM.  Then Wipe cache/Dalvik

**Comment by aaronwurtele** [comment]
https://source.android.com/setup/build/running

**Comment by dchristiansen** [comment]
We plan on building a custom ROM for a Pixel XL and then will flash the compiled ROM over ADB.

**Comment by dchristiansen** [comment]
This issue will be continued when we have compiled a ROM and plan to flash.

**Comment by aaronwurtele** [comment]
https://www.polidea.com/blog/How-to-Build-your-Own-Android-Based-on-AOSP/
this link might be helpful in the future

**Comment by dchristiansen** [comment]
Plan on installing TWRP and flash new ROM over ADB (https://pixelmantras.com/how-to-flash-custom-rom-on-google-pixel-and-pixel-xl-via-twrp/)

**Comment by aaronwurtele** [comment]
For testing we need to be able to use the debugging console in android studio or use an emulator to avoid the time consuming process of flashing. https://source.android.com/setup/build/building details the process of compiling, building, and emulating. See commit 199cc7c for details on how to build/compile everything with the droid tag.

**Comment by MLHale** [comment]
good find!

**Comment by aaronwurtele** [comment]
When we are looking to flash the device, we should use the information from here: https://source.android.com/setup/build/running#selecting-device-build

**Comment by aaronwurtele** [comment]
This likely won't be necessary considering we can show all of the functionality in Android Emulator.
